name: indian_maidan_flutter
description: Indian Maidan - Sports Turf Booking MVP
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.9.0
  razorpay_flutter: ^1.3.6
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/logo.png   # put your logo here
  #   - assets/icons/            # if you have custom icons
  # fonts:
  #   - family: Sporty
  #     fonts:
  #       - asset: assets/fonts/Sporty.ttf   # optional if you have it
